In [1]:
import numpy as np

In [97]:
n = "intention" #source 
m = "execution" #target

cost= minEditDist(n,m)

cost #cost to transform source to target 

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [ 1.  2.  3.  4.  5.  6.  7.  6.  7.  8.]
 [ 2.  3.  4.  5.  6.  7.  8.  7.  8.  7.]
 [ 3.  4.  5.  6.  7.  8.  7.  8.  9.  8.]
 [ 4.  3.  4.  5.  6.  7.  8.  9. 10.  9.]
 [ 5.  4.  5.  6.  7.  8.  9. 10. 11. 10.]
 [ 6.  5.  6.  7.  8.  9.  8.  9. 10. 11.]
 [ 7.  6.  7.  8.  9. 10.  9.  8.  9. 10.]
 [ 8.  7.  8.  9. 10. 11. 10.  9.  8.  9.]
 [ 9.  8.  9. 10. 11. 12. 11. 10.  9.  8.]]


8.0

In [96]:
def minEditDist(n,m):
    len1= len(n)
    len2= len(m)
    d= np.zeros((len1+1,len2+1)) #Creating a two-dimensional array
    
    for i in range(1,len(n)+1):
        d[i][0]= d[i-1][0] + 1
    for j in range(1,len(m)+1):
        d[0][j]= d[0][j-1] + 1
    
    for i in range(1,len(n)+1):
        #print(i)
        for j in range(1,len(m)+1):
            #print(j)
            if n[i-1] == m[j-1]:  #If the characters are the same, set the cost of substitution to zero.
                cost=0
            else:  #else set the cost to two
                cost=2
            
                
            #deletion, insertion, or substitution of a character cases 
            d[i][j]=  min(d[i-1][j] +1,
                        d[i-1][j-1] +cost ,
                         d[i][j-1] +1
                                )
                
    print(d)
    return (d[len1][len2])